version: '2'

services:
  # PostgreSQL database
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  # # Redis
  # redis:
  #   image: redis:2.8.19
  #   hostname: redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  # Django web server
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    hostname: server
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
      - rabbit
      # - redis
    depends_on:
      - db

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    volumes:
      - .:/app
    links:
      - db
      - rabbit
      # - redis
    depends_on:
      - rabbit
