# Dockerfile

FROM python:3

RUN mkdir /app
WORKDIR /app
ADD . /app/
RUN pip install -r requirements.txt

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE school.settings.production

CMD ["/app/bin/runserver"]
