# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AddField(
            model_name='user',
            name='attends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.Class'),
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(related_name='_user_parents_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='teaches_in',
            field=models.ManyToManyField(related_name='teachers', to='core.Class'),
        ),
    ]
