# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170915_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
