# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170927_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='teaches_in',
        ),
        migrations.AddField(
            model_name='classteachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_teachers', to='core.Subject'),
        ),
        migrations.AddField(
            model_name='classteachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classteachersubject',
            name='teaches_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_subjects', to='core.Class'),
        ),
        migrations.AddField(
            model_name='user',
            name='study',
            field=models.ManyToManyField(related_name='students', to='core.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='classteachersubject',
            unique_together=set([('teacher', 'subject', 'teaches_in')]),
        ),
    ]
