# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171010_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
