# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171019_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=10)),
                ('order', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('time', models.TimeField(blank=True, null=True)),
                ('class_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassTeacherSubject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('day', 'order', 'class_teacher_subject')]),
        ),
    ]
