#!/bin/bash

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

source .env/bin/activate

if [ -n "$1" ]; then
    export SERVER_ADDR="$1"

else
    export SERVER_ADDR=""

fi

honcho start
